# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'demoListWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1104, 540)
        self.listMsgNames = QtWidgets.QListWidget(Dialog)
        self.listMsgNames.setGeometry(QtCore.QRect(10, 160, 256, 192))
        self.listMsgNames.setObjectName("listMsgNames")
        self.scrollArea = QtWidgets.QScrollArea(Dialog)
        self.scrollArea.setGeometry(QtCore.QRect(10, 380, 1081, 151))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 1079, 149))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.msgContents = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.msgContents.setAutoFillBackground(True)
        self.msgContents.setFrameShape(QtWidgets.QFrame.Box)
        self.msgContents.setFrameShadow(QtWidgets.QFrame.Raised)
        self.msgContents.setText("")
        self.msgContents.setScaledContents(True)
        self.msgContents.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.msgContents.setWordWrap(True)
        self.msgContents.setObjectName("msgContents")
        self.horizontalLayout.addWidget(self.msgContents)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_2)
        self.textEditNewMsg = QtWidgets.QTextEdit(Dialog)
        self.textEditNewMsg.setGeometry(QtCore.QRect(330, 30, 321, 101))
        font = QtGui.QFont()
        font.setPointSize(34)
        self.textEditNewMsg.setFont(font)
        self.textEditNewMsg.setObjectName("textEditNewMsg")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(10, 140, 47, 13))
        self.label.setObjectName("label")
        self.listFileNames = QtWidgets.QListWidget(Dialog)
        self.listFileNames.setGeometry(QtCore.QRect(10, 30, 256, 101))
        self.listFileNames.setObjectName("listFileNames")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 47, 13))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(330, 10, 71, 16))
        self.label_3.setObjectName("label_3")
        self.btnAddMsg = QtWidgets.QPushButton(Dialog)
        self.btnAddMsg.setGeometry(QtCore.QRect(330, 150, 75, 23))
        self.btnAddMsg.setObjectName("btnAddMsg")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Messages"))
        self.label_2.setText(_translate("Dialog", "Files"))
        self.label_3.setText(_translate("Dialog", "New Message"))
        self.btnAddMsg.setText(_translate("Dialog", "Add Msg"))
