# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'demolistwidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

useKakugo = False

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(543, 555)
        font = QtGui.QFont()
        
        font.setFamilies(['UDKakugoC80Pro-DB', 'Liberation Sans'])
        
        Dialog.setFont(font)
        self.listMsgNames = QtWidgets.QListWidget(Dialog)
        self.listMsgNames.setGeometry(QtCore.QRect(280, 30, 256, 151))
        self.listMsgNames.setObjectName("listMsgNames")
        self.textEditNewMsg = QtWidgets.QTextEdit(Dialog)
        self.textEditNewMsg.setGeometry(QtCore.QRect(10, 230, 501, 101))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setKerning(False)
        self.textEditNewMsg.setFont(font)
        self.textEditNewMsg.setPlaceholderText("")
        self.textEditNewMsg.setObjectName("textEditNewMsg")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(280, 10, 47, 13))
        self.label.setObjectName("label")
        self.listFileNames = QtWidgets.QListWidget(Dialog)
        self.listFileNames.setGeometry(QtCore.QRect(10, 30, 256, 151))
        self.listFileNames.setObjectName("listFileNames")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 47, 13))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(10, 210, 71, 16))
        self.label_3.setObjectName("label_3")
        self.btnAddMsg = QtWidgets.QPushButton(Dialog)
        self.btnAddMsg.setGeometry(QtCore.QRect(260, 360, 75, 23))
        self.btnAddMsg.setObjectName("btnAddMsg")
        self.msgLabel = QtWidgets.QLineEdit(Dialog)
        self.msgLabel.setGeometry(QtCore.QRect(21, 360, 161, 20))
        self.msgLabel.setObjectName("msgLabel")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(21, 340, 101, 16))
        self.label_4.setObjectName("label_4")
        self.btnReplaceMsg = QtWidgets.QPushButton(Dialog)
        self.btnReplaceMsg.setGeometry(QtCore.QRect(340, 360, 75, 23))
        self.btnReplaceMsg.setObjectName("btnReplaceMsg")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(10, 360, 16, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(10, 410, 91, 16))
        self.label_6.setObjectName("label_6")
        self.btnSave = QtWidgets.QPushButton(Dialog)
        self.btnSave.setGeometry(QtCore.QRect(420, 360, 75, 23))
        self.btnSave.setObjectName("btnSave")
        self.msgContents = QtWidgets.QTextEdit(Dialog)
        self.msgContents.setGeometry(QtCore.QRect(10, 430, 501, 101))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setKerning(True)
        self.msgContents.setFont(font)
        self.msgContents.setReadOnly(True)
        self.msgContents.setPlaceholderText("")
        self.msgContents.setObjectName("msgContents")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Message Manager"))

        if useKakugo is True:
            self.textEditNewMsg.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'FOT-UDKakugoC80 Pro DB\'; font-size:16pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\';\"><br /></p></body></html>"))
        else:
            self.textEditNewMsg.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Liberation Sans\'; font-size:16pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\';\"><br /></p></body></html>"))
        self.label.setText(_translate("Dialog", "Messages"))
        self.label_2.setText(_translate("Dialog", "Files"))
        self.label_3.setText(_translate("Dialog", "New Message"))
        self.btnAddMsg.setText(_translate("Dialog", "Add"))
        self.label_4.setText(_translate("Dialog", "New Message Label"))
        self.btnReplaceMsg.setText(_translate("Dialog", "Replace"))
        self.label_5.setText(_translate("Dialog", "1-"))
        self.label_6.setText(_translate("Dialog", "Message Contents"))
        self.btnSave.setText(_translate("Dialog", "Save"))

        if useKakugo is True:
            self.msgContents.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'FOT-UDKakugoC80 Pro DB\'; font-size:16pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\';\"><br /></p></body></html>"))
        else:
            self.msgContents.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Liberation Sans\'; font-size:16pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\';\"><br /></p></body></html>"))
